#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
source activate qiime1

# core diversity analysis
echo "core diversity analysis"
core_diversity_analyses.py -i 2018_02_smb/otus/otu_table.biom -o 2018_02_smb/otus/core_output -m 2018_02_smb/map.tsv  -t 2018_02_smb/otus/97_otus.tree -e 30000

# deactivating environment
source deactivate
