#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py --barcode_type 12 -i Read1.fastq -b Index.fastq -o slout -m map.tsv

# counting sequences
echo "Counting sequences"
time count_seqs.py -i slout/seqs.fna

# deactivating environment
source deactivate
